### ISSUE TITLE
Pequeños cambios

### ISSUE THREAD

**Issue by ghost** [CoDevsCommunity/codevs-web-frontend#18]
Hey amigo!, aquí te dejo unos pequeños cambios para que puedas continuar con el trabajo desde donde lo dejaste, solo he limpiado un poco el codigo, usando la identación adecuada, reutilizar el app.css y ya solo te queda seguir dandole estilos al tu tutoriales.css
vamos bien!!. :3

[codevs-web-frontend.zip](https://github.com/CoDevsCommunity/codevs-web-frontend/files/6112332/codevs-web-frontend.zip)

**Comment by franciscoDevv** [comment]
eres un grande Nyan :)
